#pragma once
#include "IConfig.h"
#include <set>
#include <map>

class Configurator :public IConfig
{
	char							m_strConfigPath[260];
	bool					        m_isFreeRun;
	bool					        m_isRTDonClean;
	CardType				        m_cardType;
	ChannelMask				        m_recChannelMask;
	uint32_t                        m_nbRecChannels = 0;
	uint32_t                        m_nbRecNetCams = 0;
	uint32_t                        m_nbRecLocalCams = 0;
	ChannelMask				        m_networkChannelMask;
	ChannelMask                     m_PGMChannelMask;
	bool                            m_recPGMDirty;
	bool                            m_recPGMClean;
	Card_Config				        m_stConfig;
	LiveTGAType				        m_liveTGAType;
	char					        m_GfxNDIChannelName[NB_LIVETGA][MAX_PATH];
	char					        m_AudioMixerName[MAX_PATH] = { 0 };
	FPTVideoFormat			        m_videoFormat = FPTVideoFormat::FP_FORMAT_UNKNOWN;
	bool					        m_isHighQualityThumbnail;
	bool					        m_isDMAPlayout = false;
	WorkingMode				        m_workingMode;
	bool					        m_bAlwaysDisplayUI;
	int						        m_nbSDIRec;
	int						        m_nbStreamRec;
	bool 					        m_useExternalTCFlag;
	uint32_t				        m_ajaOutBufferThreshold;
	uint32_t				        m_maxAudioLatency, m_audioLatencySecurity;
	int						        m_nbCoreReserved;
	bool					        m_enableUHD2SI;
	bool					        m_isBuildMarker;
	bool					        m_bReduceThumbnailSendingfps;
	uint32_t				        m_rtmpOutChunkSize;
	bool					        m_bStreamInNeedSync;
	ServerType				        m_hardwareType;
	int						        m_nMaxUser = NB_MAX_USER;
	int						        m_nAJAInBufferLevel = 5;
	bool					        m_isDropNTSC = true;
	bool					        m_is720p = false;
	bool					        m_isHD = true;
	bool					        m_is4K = false;
	bool					        m_isNTSC = false;
	bool					        m_isProgressive = false;
	bool					        m_isUsingCard = true;
	float					        m_interval = 0;
	int						        m_framesPerSec = 25;
	int						        m_sendingThumbnailJump = 1;
	MemoryBaseOnServerType	        m_maxMemoryGBBaseOnServerType = MemoryBaseOnServerType::Memory_64GB;
	int						        m_frameRateNum = 25000;
	int						        m_frameRateDen = 1000;
	int						        m_videoWidth = 1920;
	int						        m_videoHeight = 1080;
	int								m_audioSampleCount = 0;
	std::string				        m_cardTypeString;
	std::string				        m_videoFormatString;
	const char*				        m_serverTypeString = nullptr;
	std::string				        m_workingModeString;
	SlowMotionMode			        m_SlowMotionMode = SlowMotionMode::SlowMotionMode_parity_violation;
	bool					        m_bPGMSubstitute = false;
	int						        m_SubstitutePlayer = 0;
	bool					        m_isInLevelA = true;
	bool					        m_isOutLevelA = true;
	LayerType				        m_layers[static_cast<size_t>(LayerType::LayerType_Max)];
	uint32_t				        m_importWaitTime; // in sec
	uint32_t				        m_udpBufSize = 0;
	FrameProviderType		        m_defaultProviderType;
	uint32_t				        m_defaultReplayJpegQuality = 63;
	uint32_t				        m_defaultPGMPRVJpegQuality = 63;
	std::string				        m_strPGM1NDIName;
	bool                            m_bStorageCRC = true;
	int						        m_nEncodeXDCamCpu = 0;
	RGBColorModel			        m_RGBColorModel = RGBColorModel::BT709;
	bool					        m_disableLiveToMixer = false;
	bool					        m_delayPGMVideo = false;
	int						        m_lowResQ4Mbps = 0;
	int						        m_lowResQ16Mbps = 0;
	int						        m_lowResFullsizeMbps = 0;
	char					        m_networkServerMulticastIP[20] = { 0 };
	char					        m_brocastDnxIP[20] = { 0 };
	char					        m_networkServerMulticastBindIP[20] = { 0 };
	char					        m_udpStreamBindIP[20] = { 0 };
	uint16_t				        m_networkServerMulticastPort = 0;
	bool					        m_BlackMagicSwapSDI = false;
	uint32_t				        m_mcuComPort = 4;
	uint32_t				        m_GPIType;
	LTCType					        m_LTCType;
	bool					        m_bFrameSenderIsUsingUdp;
	uint32_t				        m_nFrameSenderUdpPacketSize;
	ThumbnailResolution		        m_replayThumbnailResolution;
	ThumbnailResolution		        m_PGMPRVThumbnailResolution;
	Encoder264_Hardware		        m_h264EncoderHardwareType = Encoder264_Hardware::hardware_GPU;
	EncoderOut_Conversion	        m_h264OutConversion = EncoderOut_Conversion::conversion_NO;
	int						        m_NetWorkLiveGap = 0;
	bool					        m_sendCmdToNetwork = false;
	uint32_t				        m_nUdpStreamPerWait;
	uint32_t				        m_nDnxExportPerWait;
	uint32_t				        m_cacheProtectRange_HighRes = 300;
	uint32_t				        m_cacheProtectRange_LowRes = 500;
	uint32_t				        m_networkCacheProtectRange_HighRes = 300;
	uint32_t				        m_networkCacheProtectRange_LowRes = 500;
	float					        m_video_fps = 25;
	bool					        m_bAudioslomo;
	bool					        m_bAudioscrub;
	int								m_firstLocalSDICam = -1;
	int								m_firstNetworkCam_withCamIdx[NB_CAMERA] = { -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1 };
	int								m_firstNetworkCam_withServerSNPos[NB_CAMERA] = { -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1 };
	CamID                             m_map_128_to_16[NB_CAMERA] = { ID_InValidCam };//only for localCAm
	CamID                             m_map_16_to_128[NB_LOCAL_MAXCAM] = { ID_InValidCam };//only for localCAm
	char							m_strMIDIKeyWords[32];
	int	 load();
	void prepareData();
	int  setDefault();
	size_t LoadLSMConfigValue(EM_Channel_Detail& recorder, CamID  nCameraIndex, char *pValue);

public:
	Configurator();
	virtual ~Configurator() = default;
	CamID   							getFirstLocalSDICam() const override;
	const char *						getGfxNDIChannelName(int _idx) const override;
	std::string							getAudioMixerName() const override;
	LayerType							getLayers(int _l) const override;
	const bool&							is4K() const override;
	const bool&							isDropNTSC() const override;
	const bool&							is720p() const override;
	const bool&							isHD() const override;
	const bool&							isNTSC() const override;
	const bool&							isFreeRun() const override;
	const bool&							isRTDonClean() const override;
	const bool&							isProgressive() const override;
	const LiveTGAType&					getLiveTGAType() const override;
	const CardType&						getCardType() const override;
	const std::string&					getCardTypeString() const override;
	const bool&							getNeedRecPGMDirty() const override;
	const bool&							getNeedRecPGMClean() const override;
	const ChannelMask&					getRecChannelMask() const override;
	int									getNbRec() const override;
	const int&							getSDINbRec() const override;
	const int&							getStreamNbRec() const override;
	int									getNbPGM() const override;
	const ChannelMask&					getPGMChannelMask() const override;
	const Card_Config&					getCardConfig() const override;
	const float&						getInterval() const override;
	const bool&							isUsingCard() const override;
	const FPTVideoFormat&				getVideoFormat() const override;
	const std::string&					getVideoFormatString() const override;
	const int&							getFramesPerSec() const override;
	const int&							getSendingThumbnailJump() const override;
	const int&							getFrameRateNum() const override;
	const int&							getFrameRateDen() const override;
	const int&							getVideoWidth() const override;
	const int&							getVideoHeight() const override;
	const bool&							isHighQualityThumbnail() const override;
	const uint32_t&						getAudioSampleCount() const override;
	const bool&							isDMAPlayout() const override;
	bool								isBMR() const override;
	bool								isVibox() const override;
	const bool&							useExternalTimeCode() const override;
	const WorkingMode&					getWorkingMode() const override;
	const std::string&					getWorkingModeString() const override;
	const bool&							alwaysDisplayUI() const override;
	const uint32_t&						getAjaOutBufferthreshold() const override;
	const uint32_t&						getMaxAudioLatency() const override;
	const uint32_t&						getAudioLatencySecurity() const override;
	const int&							getNbCoreReserved() const override;
	const bool&							supportUHD_2SI() const override;
	const bool&							isBuildMarker() const override;
	const bool& 						needReduceThumbnailSendingfps() const override;
	const uint32_t&						getRtmpOutChunkSize() const override;
	const bool&							getStreamInNeedSync() const override;
	const ServerType&					getServerType() const override;
	const char*							getServerTypeString() const override;
	const MemoryBaseOnServerType&		getMaxMemoryGBBaseOnServerType() const override;
	const int&							getMaxUser() const override;
	const int&							getAJAInBufferLevel() const override;
	const SlowMotionMode&				getSlowMotionMode() const override;
	const bool&							isInLevelA() const override;
	const bool&							isOutLevelA() const override;
	const int&							getSubstitutePlayer() const override;
	const bool&							isPGMSubstitute() const override;
	const uint32_t&						getImportWaitTime() const override;
	const uint32_t&						getUdpBufSize() const override;
	const uint32_t&						getDefaultReplayJpegQuality() const override;
	const uint32_t&						getDefaultPGMPRVJpegQuality() const override;
	const std::string&					getPGM1NDIName() const override;
	const bool& 						isEnableStorageCRC() const override;
	const int&						    getEncodeXDCamCpu() const override;
	const RGBColorModel&				getRGBColorModel() const override;
	const bool&							getDisableLiveToMixer() const override;
	const bool&							getDelayPGMVideo() const override;
	const int&							getLowResQ4Mbps() const override;
	const int&							getLowResQ16Mbps() const override;
	const int&							getLowResFullsizeMbps() const override;
	const bool&							BlackMagicSwapSDI() const override;
	const uint32_t&						GetMCUCOMPort() const override;
	const uint32_t&						GetGPIType() const override;
	const char*							getNetworkServerMulticastIP() override;
	const uint16_t&						getNetworkServerMulticastPort() override;
	uint16_t							getNetworkServerCmdPort() override;
	const char*							getNetworkServerMulticastBindIP() override;
	const LTCType&						GetLTCType() const override;
	bool								getFrameSenderIsUsingUdp() const override;
	const uint32_t&						getFrameSenderUdpPacketSize() const override;
	uint32_t							getNetWorkLiveGap() override;
	bool								isNetworkCam(CamID cam) override;
	bool								isLocalCam(CamID cam) override;
	const ChannelMask&					getNetworkChannelMask() const override;
	bool								sendCmdToNetwork() override;
	const ThumbnailResolution&			getReplayThumbnailResolution() const override;
	const ThumbnailResolution&			getPGMPRVThumbnailResolution() const override;
	const char*							getudpStreamBindIP() override;
	const Encoder264_Hardware&          getEncoder264HardwareType() const override;
	const EncoderOut_Conversion&        getEncoder264Needconversion() const override;
	const uint32_t&						getUdpStreamPerWait() const override;
	const uint32_t&						getDnxExportPerWait() const override;
	const uint32_t&						getCacheRangeHighRes() const override;
	const uint32_t&						getCacheRangeLowRes() const override;
	const uint32_t&						getNetworkCacheRangeHighRes() const override;
	const uint32_t&						getNetworkCacheRangeLowRes() const override;
	const float&						getVideoFps() const override;
	const char*							getBrocastDnxIP() override;
	const bool&							isAudioSlomo() const override;
	const bool&							isAudioScrub() const override;
	const char*							getMIDIKeyWords() const  override;	

	// Í¨¹ý IConfig ¼Ì³Ð
	virtual int getNbRec_ALL() const override;
	virtual int getNbRec_OnlyNetCams() const override;
	virtual int getNbRec_OnlyLocalCams() const override;

protected:
	void GetCurrentPath(char buf[], char* filename);
	void IniReadValue(char* section, char* key, char* val);
	int  readStringValue(const char* section, char* key, char* val);
	int  readIntValue(const char* section, char* key);
};
